# Generated by Django 4.0.4 on 2022-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
